# Use the official Node.js LTS version as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application's source code to the working directory
COPY . .

# Build the frontend application
RUN npm run build

# Expose the port that the frontend server listens on
EXPOSE 5173

# Specify the command to run your application
CMD ["npm", "run", "dev"]