version: "3.8"

services:
  backend:
    networks:
      - shared-network
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    command: flask --app ./app/api run --port=5001

  frontend:
    networks:
      - shared-network
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - backend

networks:
  shared-network:
    driver: bridge
