version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    expose:
      - "5001"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
