# Backend Development Dockerfile
FROM python:3.9.6

RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./app ./app

# COPY . .

EXPOSE 5001

# Ensure real-time logging
ENV PYTHONUNBUFFERED=1

# Set the correct FLASK_APP environment variable
ENV FLASK_APP=app.api
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5001

# Start the Flask development server
# CMD ["flask", "run"]
CMD ["flask", "--app", "./app/api", "run", "--port=5001"]