# Backend Production Dockerfile
FROM python:3.9.6

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Expose port 5001
EXPOSE 5001

# Start the Gunicorn server
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5001", "api:app"]